import type { Evidence } from '../contracts/evidence.js';

// Ground Truth — Evidence fixtures.
//
// 36 atomic Evidence records derived from the 20 sources in
// `sources.ts`. The fixtures exercise every P0001 evidenceType
// (funding, valuation, revenue, growth, customer_adoption,
// product_launch, acquisition, policy, technology_capability,
// market_activity, usage) and the corroboration rule (an Evidence
// is supported by ≥ 1 sourceRefs; when the same fact appears in
// multiple sources, all of them are attached here).
//
// `metadata` is intentionally sparse. The same shape recurs for
// monetary amounts (currency + amount) and for period-anchored
// growth figures (period + growthRate) — the Design Review in the
// P0001 Completion Report will recommend promotion to first-class
// fields.
//
// Every Evidence has a deterministic `id` so the fixtures can be
// cross-referenced from tests. At runtime, IDs are generated with
// crypto.randomUUID() instead.

export const groundTruthEvidence: readonly Evidence[] = [
  // ── Wonderful (US) — funding, valuation, customer adoption, growth ──
  {
    id: 'ev-wonderful-series-c',
    claim: 'Wonderful raised USD 550M in a Series C financing round.',
    subject: 'Wonderful',
    evidenceType: 'funding',
    eventAt: '2026-08-30T00:00:00.000Z',
    observedAt: '2026-09-03T02:00:00.000Z',
    market: 'US',
    confidence: 'corroborated',
    sourceRefs: ['src-reuters-wonderful', 'src-techcrunch-wonderful'],
    metadata: { currency: 'USD', amount: 550_000_000, round: 'Series C' },
  },
  {
    id: 'ev-wonderful-valuation',
    claim: 'Wonderful\'s reported post-money valuation reached USD 5B.',
    subject: 'Wonderful',
    evidenceType: 'valuation',
    eventAt: '2026-08-30T00:00:00.000Z',
    observedAt: '2026-09-03T02:00:00.000Z',
    market: 'US',
    confidence: 'reported',
    sourceRefs: ['src-reuters-wonderful'],
    metadata: { currency: 'USD', amount: 5_000_000_000 },
  },
  {
    id: 'ev-wonderful-customers',
    claim: 'Wonderful reported approximately 100 enterprise customers.',
    subject: 'Wonderful',
    evidenceType: 'customer_adoption',
    eventAt: '2026-08-30T00:00:00.000Z',
    observedAt: '2026-09-03T02:00:00.000Z',
    market: 'US',
    confidence: 'corroborated',
    sourceRefs: ['src-reuters-wonderful', 'src-caixin-wonderful'],
    metadata: { count: 100, unit: 'enterprise customers' },
  },
  {
    id: 'ev-wonderful-customer-doubling',
    claim: 'Wonderful\'s enterprise customer base doubled year over year in 2026.',
    subject: 'Wonderful',
    evidenceType: 'growth',
    eventAt: '2026-08-30T00:00:00.000Z',
    observedAt: '2026-09-03T02:00:00.000Z',
    market: 'US',
    confidence: 'reported',
    sourceRefs: ['src-caixin-wonderful'],
    metadata: { period: 'YoY', factor: 2 },
  },
  {
    id: 'ev-wonderful-sequoia',
    claim: 'Wonderful\'s Series C round was led by Sequoia Capital.',
    subject: 'Wonderful',
    evidenceType: 'funding',
    eventAt: '2026-08-30T00:00:00.000Z',
    observedAt: '2026-09-03T02:00:00.000Z',
    market: 'US',
    confidence: 'reported',
    sourceRefs: ['src-reuters-wonderful'],
  },

  // ── XPeng Robotics (CN) — funding, valuation, customer adoption ──
  {
    id: 'ev-xpeng-raise',
    claim: 'XPeng Robotics raised more than USD 900M in financing.',
    subject: 'XPeng Robotics',
    evidenceType: 'funding',
    eventAt: '2026-08-25T00:00:00.000Z',
    observedAt: '2026-09-03T02:00:00.000Z',
    market: 'CN',
    confidence: 'corroborated',
    sourceRefs: ['src-xpeng-announcement', 'src-reuters-xpeng'],
    metadata: { currency: 'USD', amount: 900_000_000, threshold: 'more than' },
  },
  {
    id: 'ev-xpeng-valuation',
    claim: 'XPeng Robotics\' post-money valuation exceeded USD 6.3B.',
    subject: 'XPeng Robotics',
    evidenceType: 'valuation',
    eventAt: '2026-08-25T00:00:00.000Z',
    observedAt: '2026-09-03T02:00:00.000Z',
    market: 'CN',
    confidence: 'corroborated',
    sourceRefs: ['src-xpeng-announcement', 'src-reuters-xpeng'],
    metadata: { currency: 'USD', amount: 6_300_000_000, threshold: 'exceeded' },
  },
  {
    id: 'ev-xpeng-pilots',
    claim: 'XPeng Robotics reported over 200 enterprise pilot deployments.',
    subject: 'XPeng Robotics',
    evidenceType: 'customer_adoption',
    eventAt: '2026-08-25T00:00:00.000Z',
    observedAt: '2026-09-03T02:00:00.000Z',
    market: 'CN',
    confidence: 'primary',
    sourceRefs: ['src-xpeng-announcement'],
    metadata: { count: 200, unit: 'enterprise pilots' },
  },
  {
    id: 'ev-xpeng-alibaba',
    claim: 'XPeng Robotics\' round was led by Alibaba.',
    subject: 'XPeng Robotics',
    evidenceType: 'funding',
    eventAt: '2026-08-25T00:00:00.000Z',
    observedAt: '2026-09-03T02:00:00.000Z',
    market: 'CN',
    confidence: 'reported',
    sourceRefs: ['src-xpeng-announcement'],
  },

  // ── Prime Intellect (US) — funding, valuation, technology capability ──
  {
    id: 'ev-prime-intellect-series-a',
    claim: 'Prime Intellect closed a Series A financing round.',
    subject: 'Prime Intellect',
    evidenceType: 'funding',
    eventAt: '2026-08-30T00:00:00.000Z',
    observedAt: '2026-09-03T02:00:00.000Z',
    market: 'US',
    confidence: 'reported',
    sourceRefs: ['src-reuters-prime-intellect'],
    metadata: { round: 'Series A' },
  },
  {
    id: 'ev-prime-intellect-valuation',
    claim: 'Prime Intellect reached a reported USD 1B post-money valuation.',
    subject: 'Prime Intellect',
    evidenceType: 'valuation',
    eventAt: '2026-08-30T00:00:00.000Z',
    observedAt: '2026-09-03T02:00:00.000Z',
    market: 'US',
    confidence: 'corroborated',
    sourceRefs: ['src-reuters-prime-intellect', 'src-bloomberg-prime-intellect'],
    metadata: { currency: 'USD', amount: 1_000_000_000 },
  },
  {
    id: 'ev-prime-intellect-round-size',
    claim: 'Prime Intellect\'s Series A round totaled USD 200M.',
    subject: 'Prime Intellect',
    evidenceType: 'funding',
    eventAt: '2026-08-30T00:00:00.000Z',
    observedAt: '2026-09-03T02:00:00.000Z',
    market: 'US',
    confidence: 'reported',
    sourceRefs: ['src-reuters-prime-intellect'],
    metadata: { currency: 'USD', amount: 200_000_000, round: 'Series A' },
  },
  {
    id: 'ev-prime-intellect-distributed',
    claim: 'Prime Intellect\'s technology focuses on distributed training.',
    subject: 'Prime Intellect',
    evidenceType: 'technology_capability',
    eventAt: '2026-08-30T00:00:00.000Z',
    observedAt: '2026-09-03T02:00:00.000Z',
    market: 'US',
    confidence: 'reported',
    sourceRefs: ['src-reuters-prime-intellect'],
  },

  // ── Zhipu AI (CN) — revenue, growth, customer adoption, funding ──
  {
    id: 'ev-zhipu-growth',
    claim: 'Zhipu AI reported ARR growth of 4x year over year in 2026 H1.',
    subject: 'Zhipu AI',
    evidenceType: 'growth',
    eventAt: '2026-08-30T00:00:00.000Z',
    observedAt: '2026-09-03T02:00:00.000Z',
    market: 'CN',
    confidence: 'corroborated',
    sourceRefs: ['src-reuters-zhipu', 'src-scmp-zhipu'],
    metadata: { period: '2026 H1', factor: 4, base: 'ARR' },
  },
  {
    id: 'ev-zhipu-arr',
    claim: 'Zhipu AI reported annual recurring revenue of CNY 1B in 2026 H1.',
    subject: 'Zhipu AI',
    evidenceType: 'revenue',
    eventAt: '2026-08-30T00:00:00.000Z',
    observedAt: '2026-09-03T02:00:00.000Z',
    market: 'CN',
    confidence: 'reported',
    sourceRefs: ['src-reuters-zhipu'],
    metadata: { currency: 'CNY', amount: 1_000_000_000, period: '2026 H1' },
  },
  {
    id: 'ev-zhipu-enterprise-concentration',
    claim: 'Zhipu AI\'s revenue is concentrated in enterprise customers.',
    subject: 'Zhipu AI',
    evidenceType: 'customer_adoption',
    eventAt: '2026-08-30T00:00:00.000Z',
    observedAt: '2026-09-03T02:00:00.000Z',
    market: 'CN',
    confidence: 'reported',
    sourceRefs: ['src-reuters-zhipu'],
  },
  {
    id: 'ev-zhipu-2026-h1-raise',
    claim: 'Zhipu AI raised CNY 2B in 2026 H1.',
    subject: 'Zhipu AI',
    evidenceType: 'funding',
    eventAt: '2026-06-30T00:00:00.000Z',
    observedAt: '2026-09-03T02:00:00.000Z',
    market: 'CN',
    confidence: 'reported',
    sourceRefs: ['src-reuters-zhipu'],
    metadata: { currency: 'CNY', amount: 2_000_000_000, period: '2026 H1' },
  },

  // ── Google Gemini Enterprise (US) — product_launch, usage, technology ──
  {
    id: 'ev-gemini-launch',
    claim: 'Google launched Gemini Enterprise for industry verticals.',
    subject: 'Gemini Enterprise',
    evidenceType: 'product_launch',
    eventAt: '2026-08-15T16:00:00.000Z',
    observedAt: '2026-09-03T02:00:00.000Z',
    market: 'US',
    confidence: 'corroborated',
    sourceRefs: ['src-google-gemini-blog', 'src-techcrunch-gemini'],
  },
  {
    id: 'ev-gemini-data-isolation',
    claim: 'Gemini Enterprise added a dedicated data isolation tier.',
    subject: 'Gemini Enterprise',
    evidenceType: 'product_launch',
    eventAt: '2026-08-15T16:00:00.000Z',
    observedAt: '2026-09-03T02:00:00.000Z',
    market: 'US',
    confidence: 'primary',
    sourceRefs: ['src-google-gemini-blog'],
  },
  {
    id: 'ev-gemini-pricing',
    claim: 'Gemini Enterprise is priced at USD 30 per seat per month.',
    subject: 'Gemini Enterprise',
    evidenceType: 'usage',
    eventAt: '2026-08-15T16:00:00.000Z',
    observedAt: '2026-09-03T02:00:00.000Z',
    market: 'US',
    confidence: 'primary',
    sourceRefs: ['src-google-gemini-blog'],
    metadata: { currency: 'USD', amount: 30, unit: 'per seat per month' },
  },
  {
    id: 'ev-gemini-verticals',
    claim: 'Gemini Enterprise supports healthcare, financial services, and manufacturing verticals.',
    subject: 'Gemini Enterprise',
    evidenceType: 'technology_capability',
    eventAt: '2026-08-15T16:00:00.000Z',
    observedAt: '2026-09-03T02:00:00.000Z',
    market: 'US',
    confidence: 'primary',
    sourceRefs: ['src-google-gemini-blog'],
    metadata: { verticals: ['healthcare', 'financial services', 'manufacturing'] },
  },
  {
    id: 'ev-gemini-industry-agents',
    claim: 'Gemini Enterprise includes pre-built industry agents.',
    subject: 'Gemini Enterprise',
    evidenceType: 'product_launch',
    eventAt: '2026-08-15T16:00:00.000Z',
    observedAt: '2026-09-03T02:00:00.000Z',
    market: 'US',
    confidence: 'primary',
    sourceRefs: ['src-google-gemini-blog'],
  },

  // ── Okta / Permiso (US) — acquisition, technology capability ──
  {
    id: 'ev-okta-acquires-permiso',
    claim: 'Okta agreed to acquire Permiso.',
    subject: 'Okta / Permiso',
    evidenceType: 'acquisition',
    eventAt: '2026-09-02T15:00:00.000Z',
    observedAt: '2026-09-03T02:00:00.000Z',
    market: 'US',
    confidence: 'corroborated',
    sourceRefs: ['src-reuters-okta-permiso', 'src-okta-pr-permiso'],
  },
  {
    id: 'ev-okta-permiso-amount',
    claim: 'The Okta / Permiso transaction value was reported at USD 80M.',
    subject: 'Okta / Permiso',
    evidenceType: 'acquisition',
    eventAt: '2026-09-02T15:00:00.000Z',
    observedAt: '2026-09-03T02:00:00.000Z',
    market: 'US',
    confidence: 'reported',
    sourceRefs: ['src-reuters-okta-permiso'],
    metadata: { currency: 'USD', amount: 80_000_000 },
  },
  {
    id: 'ev-okta-permiso-close',
    claim: 'The Okta / Permiso deal is expected to close in Q3 2026.',
    subject: 'Okta / Permiso',
    evidenceType: 'acquisition',
    eventAt: '2026-09-02T15:30:00.000Z',
    observedAt: '2026-09-03T02:00:00.000Z',
    market: 'US',
    confidence: 'primary',
    sourceRefs: ['src-okta-pr-permiso'],
    metadata: { expectedClose: 'Q3 2026' },
  },
  {
    id: 'ev-permiso-threat-detection',
    claim: 'Permiso specializes in identity threat detection.',
    subject: 'Permiso',
    evidenceType: 'technology_capability',
    eventAt: '2026-09-02T15:00:00.000Z',
    observedAt: '2026-09-03T02:00:00.000Z',
    market: 'US',
    confidence: 'reported',
    sourceRefs: ['src-reuters-okta-permiso'],
  },

  // ── RoboMIND (CN) — usage, technology capability ──
  {
    id: 'ev-robomind-downloads',
    claim: 'RoboMIND dataset was downloaded more than 50,000 times.',
    subject: 'RoboMIND',
    evidenceType: 'usage',
    eventAt: '2026-08-30T00:00:00.000Z',
    observedAt: '2026-09-03T02:00:00.000Z',
    market: 'CN',
    confidence: 'corroborated',
    sourceRefs: ['src-robomind-page', 'src-huggingface-robomind'],
    metadata: { count: 50_000, threshold: 'more than' },
  },
  {
    id: 'ev-robomind-episodes',
    claim: 'RoboMIND contains more than 100,000 robot manipulation episodes.',
    subject: 'RoboMIND',
    evidenceType: 'technology_capability',
    eventAt: '2026-06-01T00:00:00.000Z',
    observedAt: '2026-09-03T02:00:00.000Z',
    market: 'CN',
    confidence: 'primary',
    sourceRefs: ['src-robomind-page'],
    metadata: { count: 100_000, threshold: 'more than' },
  },

  // ── PaXini (CN) — product_launch, technology capability ──
  {
    id: 'ev-paxini-launch',
    claim: 'PaXini launched a tactile-sensing data factory service.',
    subject: 'PaXini',
    evidenceType: 'product_launch',
    eventAt: '2026-08-20T10:00:00.000Z',
    observedAt: '2026-09-03T02:00:00.000Z',
    market: 'CN',
    confidence: 'primary',
    sourceRefs: ['src-paxini-website'],
  },
  {
    id: 'ev-paxini-modalities',
    claim: 'PaXini\'s data factory supports 7 tactile sensor modalities.',
    subject: 'PaXini',
    evidenceType: 'technology_capability',
    eventAt: '2026-08-20T10:00:00.000Z',
    observedAt: '2026-09-03T02:00:00.000Z',
    market: 'CN',
    confidence: 'primary',
    sourceRefs: ['src-paxini-website'],
    metadata: { count: 7 },
  },

  // ── China industrial robots (CN + GLOBAL) — market_activity ──
  {
    id: 'ev-china-robots-2025',
    claim: 'China industrial robot installations reached approximately 290,000 units in 2025.',
    subject: 'China industrial robotics',
    evidenceType: 'market_activity',
    eventAt: '2025-12-31T00:00:00.000Z',
    observedAt: '2026-09-03T02:00:00.000Z',
    market: 'CN',
    confidence: 'primary',
    sourceRefs: ['src-ifr-china-robots'],
    metadata: { period: '2025', unit: 'units', count: 290_000 },
  },
  {
    id: 'ev-china-robots-growth',
    claim: 'China industrial robot installations grew approximately 18% year over year in 2025.',
    subject: 'China industrial robotics',
    evidenceType: 'market_activity',
    eventAt: '2025-12-31T00:00:00.000Z',
    observedAt: '2026-09-03T02:00:00.000Z',
    market: 'CN',
    confidence: 'corroborated',
    sourceRefs: ['src-ifr-china-robots', 'src-reuters-china-robots'],
    metadata: { period: '2025', growthRate: 0.18 },
  },
  {
    id: 'ev-global-robots-growth',
    claim: 'Global industrial robot installations grew approximately 12% year over year in 2025.',
    subject: 'Global industrial robotics',
    evidenceType: 'market_activity',
    eventAt: '2025-12-31T00:00:00.000Z',
    observedAt: '2026-09-03T02:00:00.000Z',
    market: 'GLOBAL',
    confidence: 'primary',
    sourceRefs: ['src-ifr-china-robots'],
    metadata: { period: '2025', growthRate: 0.12 },
  },

  // ── China policy (CN) — policy, market_activity ──
  {
    id: 'ev-state-council-embodied',
    claim: 'China\'s State Council issued guiding opinions on embodied-AI training data.',
    subject: 'China State Council',
    evidenceType: 'policy',
    eventAt: '2026-05-15T00:00:00.000Z',
    observedAt: '2026-09-03T02:00:00.000Z',
    market: 'CN',
    confidence: 'primary',
    sourceRefs: ['src-state-council-embodied'],
  },
  {
    id: 'ev-mofcom-digital-export',
    claim: 'China\'s MOFCOM released digital export guidelines for 2026.',
    subject: 'China MOFCOM',
    evidenceType: 'policy',
    eventAt: '2026-04-10T00:00:00.000Z',
    observedAt: '2026-09-03T02:00:00.000Z',
    market: 'CN',
    confidence: 'primary',
    sourceRefs: ['src-mofcom-digital-exports'],
  },
  {
    id: 'ev-china-digital-exports',
    claim: 'China\'s digital exports were valued at USD 350B in 2025.',
    subject: 'China digital exports',
    evidenceType: 'market_activity',
    eventAt: '2025-12-31T00:00:00.000Z',
    observedAt: '2026-09-03T02:00:00.000Z',
    market: 'CN',
    confidence: 'reported',
    sourceRefs: ['src-mofcom-digital-exports'],
    metadata: { currency: 'USD', amount: 350_000_000_000, period: '2025' },
  },
];
